// Generated by scripts/hooks/firmware_config_gen.py from ShowControl/network.json.
// Do not edit by hand — edit network.json and re-run the script.

#pragma once

#define CG_LAN_GATEWAY { 192, 168, 1, 1 }
#define CG_LAN_NETMASK { 255, 255, 255, 0 }

// treehouse_swannatopia
#define CG_IP_SWANNATOPIA { 192, 168, 1, 60 }
#define CG_IP_STR_SWANNATOPIA "192.168.1.60"
#define CG_OSC_PORT_SWANNATOPIA 9000

// treehouse_julia
#define CG_IP_JULIA { 192, 168, 1, 61 }
#define CG_IP_STR_JULIA "192.168.1.61"
#define CG_OSC_PORT_JULIA 9000

// treehouse_jess
#define CG_IP_JESS { 192, 168, 1, 62 }
#define CG_IP_STR_JESS "192.168.1.62"
#define CG_OSC_PORT_JESS 9000

// treehouse_dormer
#define CG_IP_DORMER { 192, 168, 1, 63 }
#define CG_IP_STR_DORMER "192.168.1.63"
#define CG_OSC_PORT_DORMER 9000
