#!/usr/bin/env bash
# setup_pico_udev.sh — assign stable /dev/treehouse-pico-{a,b} and
# /dev/treehouse-branches symlinks via udev rules keyed on USB serial number.
#
# Plug in Pico A (dioramas), Pico B (structure), and branch controller
# BEFORE running this script. Run as root:
#
#   sudo bash ShowControl/TreeHouse/deploy/setup_pico_udev.sh
set -e

RULES_FILE="/etc/udev/rules.d/99-treehouse-picos.rules"

if [ "$EUID" -ne 0 ]; then
    echo "Error: run as root — sudo bash $0"
    exit 1
fi

echo "=== TreeHouse Pico udev setup ==="
echo ""
echo "Detected USB serial devices:"
echo ""

# Enumerate /dev/ttyACMx and /dev/ttyUSBx with serial numbers
DEVICES=()
i=0
for dev in /dev/ttyACM* /dev/ttyUSB*; do
    [ -e "$dev" ] || continue
    serial=$(udevadm info -q all -n "$dev" 2>/dev/null | grep 'ID_SERIAL_SHORT=' | cut -d= -f2)
    vendor=$(udevadm info -q all -n "$dev" 2>/dev/null | grep 'ID_VENDOR_ID='    | cut -d= -f2)
    model=$(udevadm info  -q all -n "$dev" 2>/dev/null | grep 'ID_MODEL='        | cut -d= -f2 | head -1)
    printf "  [%d] %-15s  serial=%-20s  %s/%s\n" "$i" "$dev" "${serial:-(none)}" "$vendor" "$model"
    DEVICES+=("$dev:$serial")
    i=$((i+1))
done

if [ ${#DEVICES[@]} -eq 0 ]; then
    echo "  No USB serial devices found. Plug in Picos and re-run."
    exit 1
fi

echo ""
echo "Enter device number for each role (or press Enter to skip):"
echo ""

pick_serial() {
    local role="$1"
    local idx
    read -rp "  $role → device number: " idx
    [ -z "$idx" ] && echo "" && return
    local entry="${DEVICES[$idx]}"
    echo "${entry#*:}"
}

SERIAL_A=$(pick_serial "Pico A — dioramas (/dev/treehouse-pico-a)")
SERIAL_B=$(pick_serial "Pico B — structure (/dev/treehouse-pico-b)")
SERIAL_BR=$(pick_serial "Branch controller  (/dev/treehouse-branches)")

echo ""
echo "Writing $RULES_FILE ..."

{
    echo '# TreeHouse stable device names — generated by setup_pico_udev.sh'
    echo '# Regenerate: sudo bash ShowControl/TreeHouse/deploy/setup_pico_udev.sh'
    echo ''
    if [ -n "$SERIAL_A" ]; then
        echo "SUBSYSTEM==\"tty\", ATTRS{serial}==\"${SERIAL_A}\", SYMLINK+=\"treehouse-pico-a\", MODE=\"0666\""
    fi
    if [ -n "$SERIAL_B" ]; then
        echo "SUBSYSTEM==\"tty\", ATTRS{serial}==\"${SERIAL_B}\", SYMLINK+=\"treehouse-pico-b\", MODE=\"0666\""
    fi
    if [ -n "$SERIAL_BR" ]; then
        echo "SUBSYSTEM==\"tty\", ATTRS{serial}==\"${SERIAL_BR}\", SYMLINK+=\"treehouse-branches\", MODE=\"0666\""
    fi
} > "$RULES_FILE"

cat "$RULES_FILE"
echo ""

udevadm control --reload-rules
udevadm trigger

echo "Waiting for symlinks..."
sleep 2

for sym in treehouse-pico-a treehouse-pico-b treehouse-branches; do
    if [ -L "/dev/$sym" ]; then
        echo "  ✓ /dev/$sym → $(readlink /dev/$sym)"
    else
        echo "  ✗ /dev/$sym — not found (check cable / serial number)"
    fi
done

echo ""
echo "=== Done. Replug devices if symlinks are missing. ==="
