#!/usr/bin/env python3
"""
Generates firmware network headers from ShowControl/network.json.

Two ways to run it:

  * As a Claude Code hook — receives the tool-use JSON on stdin and exits
    immediately unless the edited file was network.json.
  * By hand — ``python3 scripts/hooks/firmware_config_gen.py`` regenerates
    everything unconditionally. Do this before flashing.

network.json is the single source of truth for every address on the Show
Network (AGENTS.md constraint #3). Firmware never hardcodes an IP; it includes
the header this script writes.

Currently generated:

  Firmware/TreeHouse_Controllers/include/net_config.h   (ADR-0020)

TODO: generate Firmware/FlowerBeds_Follow_ServoController/config.h too.
"""
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
NETWORK_JSON = REPO_ROOT / "ShowControl" / "network.json"
TREEHOUSE_HEADER = (
    REPO_ROOT / "Firmware" / "TreeHouse_Controllers" / "include" / "net_config.h"
)

# Firmware key in network.json → CG_TARGET_* macro suffix used by platformio.ini.
TREEHOUSE_LOCATIONS = {
    "treehouse_swannatopia": "SWANNATOPIA",
    "treehouse_julia": "JULIA",
    "treehouse_jess": "JESS",
    "treehouse_dormer": "DORMER",
}


def _octets(name: str, dotted: str) -> str:
    parts = dotted.split(".")
    if len(parts) != 4 or not all(p.isdigit() and 0 <= int(p) <= 255 for p in parts):
        raise ValueError(f"{name}: {dotted!r} is not a dotted-quad IPv4 address")
    return ", ".join(parts)


def render_treehouse_header(network: dict) -> str:
    lan = network.get("lan", {})
    gateway = lan.get("gateway")
    netmask = lan.get("netmask")
    if not gateway or not netmask:
        raise ValueError("network.json needs a 'lan' block with 'gateway' and 'netmask'")

    firmware = network.get("firmware", {})
    missing = [k for k in TREEHOUSE_LOCATIONS if k not in firmware]
    if missing:
        raise ValueError(f"network.json is missing firmware entries: {', '.join(missing)}")

    lines = [
        "// Generated by scripts/hooks/firmware_config_gen.py from ShowControl/network.json.",
        "// Do not edit by hand — edit network.json and re-run the script.",
        "",
        "#pragma once",
        "",
        f"#define CG_LAN_GATEWAY {{ {_octets('lan.gateway', gateway)} }}",
        f"#define CG_LAN_NETMASK {{ {_octets('lan.netmask', netmask)} }}",
        "",
    ]

    for key, macro in TREEHOUSE_LOCATIONS.items():
        entry = firmware[key]
        ip = entry.get("ip")
        port = entry.get("osc_port")
        if not ip or not port:
            raise ValueError(f"network.json: firmware.{key} needs both 'ip' and 'osc_port'")
        lines += [
            f"// {key}",
            f"#define CG_IP_{macro} {{ {_octets(key + '.ip', ip)} }}",
            f"#define CG_IP_STR_{macro} \"{ip}\"",
            f"#define CG_OSC_PORT_{macro} {int(port)}",
            "",
        ]

    return "\n".join(lines)


def generate() -> list[Path]:
    network = json.loads(NETWORK_JSON.read_text())
    TREEHOUSE_HEADER.parent.mkdir(parents=True, exist_ok=True)
    TREEHOUSE_HEADER.write_text(render_treehouse_header(network))
    return [TREEHOUSE_HEADER]


def main() -> None:
    if not sys.stdin.isatty():
        raw = sys.stdin.read()
        if raw.strip():
            data = json.loads(raw)
            file_path = data.get("tool_input", {}).get("file_path", "")
            if "network.json" not in file_path:
                sys.exit(0)

    for path in generate():
        print(f"regenerated {path.relative_to(REPO_ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
